"""
Django settings for ComunidadSoft project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# La configuración sensible se lee de variables de entorno (ver .env / Docker).
# Si no existen, usa valores por defecto pensados para desarrollo local.

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-=pf^8&g#t4v2i#qz2c8^q6z0i@z2b$fecq##wl7awnkokv3glw',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes', 'on')

ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()
]

# Necesario para los POST (login, guardar predicción) detrás de un proxy/HTTPS
# como Cloudflare Tunnel. Ej: https://prode.ies9018malargue.edu.ar
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'prode',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise sirve los archivos estáticos (CSS del admin, etc.) en producción
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ComunidadSoft.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ComunidadSoft.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Se configura desde la variable de entorno DATABASE_URL (dj-database-url).
# - Producción / Docker: postgres://user:pass@host:5432/db (backend postgresql)
# - Desarrollo local: si no hay DATABASE_URL, cae a SQLite.
DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=int(os.environ.get('DB_CONN_MAX_AGE', '60')),
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Redirecciones del sistema de autenticación nativo
LOGIN_REDIRECT_URL = '/'       # Al loguearse, va directo al index (panel del prode)
LOGOUT_REDIRECT_URL = '/accounts/login/'  # Al desloguearse, vuelve al formulario

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Detrás de un reverse proxy / Cloudflare Tunnel que termina el HTTPS.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# SofaScore - sincronización de fixture y resultados.
# Backend: auto (RapidAPI y fallback direct), rapidapi o direct (curl_cffi).
SOFASCORE_BACKEND = os.environ.get('SOFASCORE_BACKEND', 'auto')
RAPIDAPI_KEY = os.environ.get('RAPIDAPI_KEY', '')
RAPIDAPI_HOST = os.environ.get('RAPIDAPI_HOST', 'sofascore.p.rapidapi.com')
RAPIDAPI_TIMEOUT = int(os.environ.get('RAPIDAPI_TIMEOUT', '30'))
SOFASCORE_SPORT = os.environ.get('SOFASCORE_SPORT', 'football')
SOFASCORE_TOURNAMENT_ID = int(os.environ.get('SOFASCORE_TOURNAMENT_ID', '0'))

# Calendario del Mundial 2026 para inferir fase si la API no trae round claro.
SOFASCORE_GRUPOS_DESDE = os.environ.get('SOFASCORE_GRUPOS_DESDE', '2026-06-11')
SOFASCORE_GRUPOS_HASTA = os.environ.get('SOFASCORE_GRUPOS_HASTA', '2026-06-27')
SOFASCORE_FASE_FECHAS = {
    'DIECISEISAVOS': ('2026-06-28', '2026-07-03'),
    'OCTAVOS': ('2026-07-04', '2026-07-07'),
    'CUARTOS': ('2026-07-10', '2026-07-11'),
    'SEMI': ('2026-07-14', '2026-07-15'),
    'TERCERO': ('2026-07-18', '2026-07-18'),
    'FINAL': ('2026-07-19', '2026-07-19'),
}
