# Generated by Django 6.0.6 on 2026-06-05 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_local', models.CharField(max_length=50)),
                ('codigo_local', models.CharField(help_text='Código ISO minúscula, ej: ar, br, fr', max_length=2)),
                ('equipo_visitante', models.CharField(max_length=50)),
                ('codigo_visitante', models.CharField(help_text='Código ISO minúscula', max_length=2)),
                ('fecha_hora', models.DateTimeField()),
                ('zona', models.CharField(help_text='Ej: Grupo A, Octavos 1, etc.', max_length=20)),
                ('fase', models.CharField(choices=[('GRUPOS', 'Fase de Grupos'), ('OCTAVOS', 'Octavos de Final'), ('CUARTOS', 'Cuartos de Final'), ('SEMI', 'Semifinal'), ('TERCERO', 'Tercer Puesto'), ('FINAL', 'Final')], default='GRUPOS', max_length=15)),
                ('goles_local_real', models.IntegerField(blank=True, null=True)),
                ('goles_visitante_real', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles_local_pred', models.IntegerField()),
                ('goles_visitante_pred', models.IntegerField()),
                ('puntos_ganados', models.IntegerField(default=0)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='prode.partido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'partido')},
            },
        ),
    ]
