# Generated by Django 6.0.6 on 2026-06-09 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(db_index=True, unique=True)),
                ('equipo_local', models.CharField(max_length=80)),
                ('equipo_visitante', models.CharField(max_length=80)),
                ('codigo_local', models.CharField(blank=True, max_length=2)),
                ('codigo_visitante', models.CharField(blank=True, max_length=2)),
                ('logo_local', models.URLField(blank=True)),
                ('logo_visitante', models.URLField(blank=True)),
                ('goles_local', models.IntegerField(blank=True, null=True)),
                ('goles_visitante', models.IntegerField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_CURSO', 'En curso'), ('FINALIZADO', 'Finalizado')], db_index=True, default='PENDIENTE', max_length=12)),
                ('fase', models.CharField(choices=[('GRUPOS', 'Fase de Grupos'), ('OCTAVOS', 'Octavos de Final'), ('CUARTOS', 'Cuartos de Final'), ('SEMI', 'Semifinal'), ('TERCERO', 'Tercer Puesto'), ('FINAL', 'Final')], default='GRUPOS', max_length=15)),
                ('zona', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'ordering': ['fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_totales', models.IntegerField(db_index=True, default=0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles_local_apostado', models.IntegerField()),
                ('goles_visitante_apostado', models.IntegerField()),
                ('puntos_obtenidos', models.IntegerField(default=0)),
                ('procesada', models.BooleanField(db_index=True, default=False)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='prode.partido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'partido')},
            },
        ),
    ]
