"""Ajustes de campos + reparación del esquema legacy del Prode original.

En servidores que desplegaron la primera versión del proyecto, PostgreSQL puede
tener el esquema viejo (sin api_id/estado, goles_local_real, etc.) mientras
django_migrations marca 0001_initial como aplicada. Esta migración detecta ese
caso y actualiza el esquema antes de aplicar los ALTER finales.
"""

from django.db import migrations, models


def _columnas(cursor, tabla):
    cursor.execute(
        """
        SELECT column_name
        FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = %s
        """,
        [tabla],
    )
    return {row[0] for row in cursor.fetchall()}


def _tabla_existe(cursor, tabla):
    cursor.execute(
        """
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = %s
        """,
        [tabla],
    )
    return cursor.fetchone() is not None


def reparar_esquema_legacy(apps, schema_editor):
    """Actualiza el esquema viejo al nuevo si hace falta."""
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        if not _tabla_existe(cursor, 'prode_partido'):
            return

        cols = _columnas(cursor, 'prode_partido')
        if 'estado' in cols:
            # Ya está en el esquema nuevo; los AlterField de abajo alcanzan.
            return

        # --- prode_partido: esquema original → esquema actual ---
        if 'api_id' not in cols:
            cursor.execute(
                'ALTER TABLE prode_partido '
                'ADD COLUMN api_id integer UNIQUE'
            )
            cursor.execute(
                'CREATE INDEX IF NOT EXISTS prode_partido_api_id_idx '
                'ON prode_partido (api_id)'
            )

        if 'logo_local' not in cols:
            cursor.execute(
                "ALTER TABLE prode_partido "
                "ADD COLUMN logo_local varchar(200) NOT NULL DEFAULT ''"
            )
        if 'logo_visitante' not in cols:
            cursor.execute(
                "ALTER TABLE prode_partido "
                "ADD COLUMN logo_visitante varchar(200) NOT NULL DEFAULT ''"
            )

        if 'goles_local_real' in cols and 'goles_local' not in cols:
            cursor.execute(
                'ALTER TABLE prode_partido '
                'RENAME COLUMN goles_local_real TO goles_local'
            )
        elif 'goles_local' not in cols:
            cursor.execute(
                'ALTER TABLE prode_partido ADD COLUMN goles_local integer'
            )

        if 'goles_visitante_real' in cols and 'goles_visitante' not in cols:
            cursor.execute(
                'ALTER TABLE prode_partido '
                'RENAME COLUMN goles_visitante_real TO goles_visitante'
            )
        elif 'goles_visitante' not in cols:
            cursor.execute(
                'ALTER TABLE prode_partido ADD COLUMN goles_visitante integer'
            )

        cursor.execute(
            "ALTER TABLE prode_partido "
            "ADD COLUMN estado varchar(20) NOT NULL DEFAULT 'PENDIENTE'"
        )
        cursor.execute(
            'CREATE INDEX IF NOT EXISTS prode_partido_estado_idx '
            'ON prode_partido (estado)'
        )

        # --- prode_prediccion ---
        if _tabla_existe(cursor, 'prode_prediccion'):
            pcols = _columnas(cursor, 'prode_prediccion')

            if 'goles_local_pred' in pcols:
                cursor.execute(
                    'ALTER TABLE prode_prediccion '
                    'RENAME COLUMN goles_local_pred TO goles_local_apostado'
                )
            if 'goles_visitante_pred' in pcols:
                cursor.execute(
                    'ALTER TABLE prode_prediccion '
                    'RENAME COLUMN goles_visitante_pred '
                    'TO goles_visitante_apostado'
                )
            if 'puntos_ganados' in pcols:
                cursor.execute(
                    'ALTER TABLE prode_prediccion '
                    'RENAME COLUMN puntos_ganados TO puntos_obtenidos'
                )
            if 'procesada' not in pcols:
                cursor.execute(
                    'ALTER TABLE prode_prediccion '
                    'ADD COLUMN procesada boolean NOT NULL DEFAULT false'
                )
                cursor.execute(
                    'CREATE INDEX IF NOT EXISTS prode_prediccion_procesada_idx '
                    'ON prode_prediccion (procesada)'
                )

        # --- prode_perfilusuario (no existía en la versión original) ---
        if not _tabla_existe(cursor, 'prode_perfilusuario'):
            cursor.execute("""
                CREATE TABLE prode_perfilusuario (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    puntos_totales integer NOT NULL DEFAULT 0,
                    usuario_id bigint NOT NULL UNIQUE
                        REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
                )
            """)
            cursor.execute(
                'CREATE INDEX prode_perfilusuario_puntos_totales_idx '
                'ON prode_perfilusuario (puntos_totales)'
            )


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(reparar_esquema_legacy, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='partido',
            name='equipo_local',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='partido',
            name='equipo_visitante',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='partido',
            name='estado',
            field=models.CharField(
                choices=[
                    ('PENDIENTE', 'Pendiente'),
                    ('EN_CURSO', 'En curso'),
                    ('FINALIZADO', 'Finalizado'),
                ],
                db_index=True,
                default='PENDIENTE',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='partido',
            name='fecha_hora',
            field=models.DateTimeField(db_index=True),
        ),
    ]
