# Generated by Django 6.0.6 on 2026-06-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='equipo_local',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='partido',
            name='equipo_visitante',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='partido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_CURSO', 'En curso'), ('FINALIZADO', 'Finalizado')], db_index=True, default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='partido',
            name='fecha_hora',
            field=models.DateTimeField(db_index=True),
        ),
    ]
